export const topicTags = [
  "add",
  "topic: operators",
  "advanced task",
  "analyze",
  "apply",
  "argue",
  "assign",
  "bundle",
  "categorize",
  "change",
  "choose",
  "classify",
  "collect",
  "combine",
  "compare",
  "compound",
  "comprehend",
  "compress",
  "consolidate",
  "construct",
  "continue",
  "copy",
  "create",
  "critically",
  "data analysis",
  "topic: data and chance",
  "decompose",
  "deepen",
  "derive",
  "describe",
  "die",
  "topic: games and puzzles",
  "differentiate",
  "distinguish",
  "draw",
  "enumerate",
  "evaluate",
  "execute",
  "explain",
  "extract",
  "find",
  "fold",
  "game",
  "identify",
  "infer",
  "integrate",
  "interpret",
  "investigate",
  "justify",
  "list",
  "measure",
  "model",
  "topic: representation forms",
  "move",
  "name",
  "order",
  "place",
  "place down",
  "plan",
  "predict",
  "problem solving",
  "proof",
  "question",
  "read",
  "rearrange",
  "recognize",
  "reconstruct",
  "reflect",
  "represent",
  "research",
  "sketch",
  "solution procedure",
  "solve",
  "sort",
  "strategy",
  "stretch",
  "structure",
  "subtract",
  "systematically",
  "systematize",
  "transform",
  "translate",
  "trial and error",
  "understand",
  "verify",
  "vie",
  "win",
  "budget",
  "financial mathematics",
  "compound interest",
  "interest",
  "currency",
  "discount",
  "example",
  "topic: text and word problems",
  "topic: money",
  "interest rate",
  "loss",
  "mental manipulation",
  "preposition",
  "principal",
  "profit",
  "puzzle",
  "real world",
  "sensory",
  "source",
  "tax",
  "text",
  "rule for divisibility by 10",
  "topic: divisibility rules",
  "rule for divisibility by 100",
  "rule for divisibility by 11",
  "rule for divisibility by 2",
  "rule for divisibility by 25",
  "rule for divisibility by 3",
  "rule for divisibility by 4",
  "rule for divisibility by 5",
  "rule for divisibility by 50",
  "rule for divisibility by 6",
  "rule for divisibility by 7",
  "rule for divisibility by 8",
  "rule for divisibility by 9",
  "a-b-c-formula",
  "quadratic formula",
  "zero",
  "addition",
  "basic arithmetic operation",
  "algebraic field",
  "topic: algebra and expressions",
  "approximate",
  "arithmetic sequence",
  "sequence",
  "arithmetic symbol",
  "notation",
  "average",
  "backward",
  "counting",
  "base (exponentiation)",
  "power",
  "base value",
  "percentage",
  "topic: arithmetic",
  "basis (vector space)",
  "vector",
  "binomial formula",
  "formula",
  "bracket",
  "calculate",
  "calculation story",
  "common denominator",
  "denominator",
  "complex number",
  "number system",
  "complex plane",
  "plane",
  "convert",
  "topic: numbers and sets",
  "cross product",
  "cube root",
  "root",
  "decimal",
  "denomination",
  "fraction",
  "determinant",
  "matrix",
  "difference",
  "subtraction",
  "digit",
  "divisibility",
  "division",
  "divisor",
  "domain",
  "function",
  "elimination method",
  "system of linear equation",
  "equality",
  "equating method",
  "equation",
  "equivalence transformation",
  "equivalent fraction",
  "estimate",
  "even number",
  "integer",
  "expand",
  "expansion",
  "factor out",
  "factorial",
  "combinatorics",
  "factoring",
  "fixed vector",
  "forward",
  "four",
  "gaussian elimination",
  "geometric sequence",
  "greatest common divisor",
  "inequality",
  "infinite set",
  "set",
  "infinity",
  "integer exponent",
  "inverse",
  "inverse matrix",
  "inverse operation",
  "operation",
  "irrational number",
  "large number",
  "least common multiple",
  "linear algebra",
  "topic: space and shape",
  "linear combination",
  "linear dependence",
  "literal equation",
  "magnitude",
  "making 10",
  "mental math",
  "matrix multiplication",
  "multiplication",
  "multiplication table",
  "natural number",
  "natural number exponent",
  "negative exponent",
  "negative number",
  "neighbor",
  "no decimal",
  "no largest element",
  "number sequence",
  "number system expansion",
  "numerator",
  "odd number",
  "one",
  "operator",
  "opposite",
  "topic: properties and relations",
  "opposite number",
  "p-q-formula",
  "parameter",
  "pattern",
  "per mille",
  "topic: measurement",
  "percentage rate",
  "percentage value",
  "place value",
  "placeholder",
  "polar form",
  "polynomial",
  "polynomial division",
  "positive number line",
  "number line",
  "power of ten",
  "prime number",
  "proportion",
  "ratio",
  "rational number",
  "real number",
  "reciprocal",
  "remainder",
  "repeated",
  "repeating decimal",
  "result",
  "root (radical)",
  "rounding",
  "scalar",
  "scalar product",
  "sign",
  "simplify",
  "solution set",
  "square number",
  "subset",
  "substitute",
  "substitution method",
  "term",
  "three",
  "tuple",
  "two",
  "two-digit",
  "two-step",
  "variable",
  "zero product property",
  "are",
  "unit",
  "area",
  "geometry",
  "base area",
  "solid",
  "cent",
  "euro",
  "centimeter",
  "centimeter squared",
  "centimeter cubed",
  "decimeter",
  "decimeter squared",
  "decimeter cubed",
  "degree",
  "angle",
  "distance",
  "length",
  "hectare",
  "gram",
  "kilogram",
  "kilometer",
  "kilometer squared",
  "kilometer cubed",
  "liter",
  "length measurement",
  "measurement",
  "meter",
  "meter squared",
  "meter cubed",
  "mass",
  "mass measurement",
  "measurement device",
  "milliliter",
  "millimeter",
  "millimeter squared",
  "millimeter cubed",
  "perimeter",
  "point in time",
  "radians",
  "scale",
  "scaling",
  "side length",
  "size",
  "surface",
  "surface area",
  "time measurement",
  "tonne",
  "second",
  "minute",
  "hour",
  "day",
  "month",
  "year",
  "unit prefix",
  "nano",
  "micro",
  "mega",
  "giga",
  "tera",
  "volume",
  "2d coordinate plane",
  "2d shape",
  "shape",
  "3d coordinate",
  "acute angle",
  "alternate angle",
  "altitude",
  "angle bisector",
  "annulus",
  "circle",
  "arc",
  "axis symmetry",
  "symmetry",
  "base (geometry)",
  "cavalieri's principle",
  "center",
  "center of dilation",
  "dilation",
  "central angle",
  "centroid",
  "chord",
  "line segment",
  "circumcircle",
  "cone",
  "congruence",
  "congruence postulate",
  "coordinate form",
  "coordinate-free form",
  "corresponding angle",
  "cube",
  "cuboid",
  "prism",
  "curvature",
  "curved",
  "cylinder",
  "degree (angle)",
  "diameter",
  "geometric transformation",
  "direction",
  "edge",
  "equilateral triangle",
  "triangle",
  "face",
  "geometric mean theorem",
  "theorem",
  "height",
  "hessian normal form",
  "normal form",
  "human body",
  "incircle",
  "inner",
  "position",
  "intercept theorem",
  "interior angle sum",
  "intersecting line",
  "relative position",
  "isosceles triangle",
  "kite",
  "quadrilateral",
  "leg theorem",
  "line",
  "line-line",
  "line-plane",
  "median of a triangle",
  "mid-perpendicular",
  "perpendicular",
  "midpoint",
  "point",
  "mirror image",
  "reflection",
  "net",
  "normal",
  "normal vector",
  "object",
  "oblique image",
  "oblique solid",
  "obtuse angle",
  "origin",
  "parallel line",
  "parallelogram",
  "parameter form",
  "path",
  "perpendicular bisector",
  "perpendicular line",
  "plane equation",
  "plane-plane",
  "point symmetry",
  "point-line",
  "point-plane",
  "point-point",
  "polygon",
  "pyramid",
  "pythagorean theorem",
  "right triangle",
  "quadrant",
  "radius",
  "ray",
  "rectangle",
  "reflex angle",
  "regular polygon",
  "rhombus",
  "right angle",
  "right cone",
  "right cylinder",
  "right prism",
  "right pyramid",
  "rotation",
  "rotation direction",
  "rotational symmetry",
  "round (shape)",
  "secant",
  "sector",
  "similarity",
  "skew line",
  "spatial awareness",
  "sphere",
  "square",
  "square pyramid",
  "straight angle",
  "tessellation",
  "thales' theorem",
  "translation",
  "transversal",
  "trapezoid",
  "vertex",
  "view",
  "3rd degree polynomial",
  "topic: functional relationship",
  "4th degree polynomial",
  "absolute value",
  "amplitude",
  "absolute",
  "antiderivative",
  "area under curve",
  "asymptote",
  "average rate of change",
  "calculus",
  "chain rule",
  "chain rule (differentiation)",
  "chain rule (integration)",
  "completing the square",
  "quadratic",
  "topic: methods and tools",
  "composite function",
  "constant multiple rule",
  "composite",
  "constant multiple rule (differentiation)",
  "constant multiple rule (integration)",
  "constant rate of change",
  "constant rule",
  "rate of change",
  "constant rule (differentiation)",
  "constant rule (integration)",
  "continuity",
  "continuous",
  "convergence",
  "cosine",
  "trigonometric",
  "curve sketching",
  "degree of a polynomial",
  "derivative",
  "difference quotient",
  "differentiability",
  "differential equation",
  "differentiation rule",
  "end behavior",
  "equation of a tangent line",
  "tangent line",
  "exponential",
  "exponential equation",
  "extremum",
  "family",
  "family of function",
  "fundamental theorem of calculus",
  "global maximum",
  "maximum",
  "global minimum",
  "minimum",
  "graph",
  "growth factor",
  "higher-order derivative",
  "improper integral",
  "integral",
  "inflection point",
  "initial value",
  "integration by substitution",
  "integration rule",
  "intercept",
  "intersection",
  "interval",
  "inverse function",
  "law of cosine",
  "law of sine",
  "sine",
  "limit",
  "limit of integration",
  "linear",
  "local maximum",
  "local minimum",
  "local rate of change",
  "locus",
  "logarithm",
  "logarithm law",
  "lower sum",
  "monotonicity",
  "natural logarithm",
  "normal line",
  "optimization",
  "period",
  "periodic",
  "power rule",
  "power rule (differentiation)",
  "power rule (integration)",
  "product rule",
  "product rule (differentiation)",
  "product rule (integration)",
  "range (function)",
  "rational function",
  "root function",
  "saddle point",
  "second derivative",
  "signed area",
  "slope",
  "slope triangle",
  "solid of revolution",
  "standard form",
  "start value",
  "value",
  "sum rule",
  "sum rule (differentiation)",
  "sum rule (integration)",
  "tangent",
  "unit circle",
  "upper sum",
  "vertex form",
  "absolute frequency",
  "frequency",
  "alternative hypothesis",
  "hypothesis testing",
  "arithmetic mean",
  "measure of central tendency",
  "bayes' theorem",
  "conditional probability",
  "bernoulli trial",
  "random experiment",
  "binomial coefficient",
  "binomial distribution",
  "distribution",
  "complementary event",
  "event",
  "probability",
  "confidence interval",
  "counting principle",
  "cumulative distribution",
  "data",
  "data manipulation",
  "data representation",
  "error analysis",
  "expected value",
  "laplace experiment",
  "law of large number",
  "law of total probability",
  "markov chain",
  "stochastic process",
  "mean absolute deviation",
  "measure of dispersion",
  "median",
  "mode",
  "moivre-laplace",
  "normal distribution",
  "mutually exclusive",
  "null hypothesis",
  "path rule",
  "tree diagram",
  "permutation",
  "population",
  "statistics",
  "prediction interval",
  "quartile",
  "random number generator",
  "topic: tools and technology",
  "simulation",
  "random process",
  "range",
  "ranking",
  "rarest value",
  "raw data",
  "rejection region",
  "relative",
  "sample",
  "sample space",
  "sigma rule",
  "significance level",
  "standard deviation",
  "statistical power",
  "stochastics",
  "stochastic variable",
  "sum rule (probability)",
  "survey",
  "transition matrix",
  "type i error",
  "type ii error",
  "union",
  "urn model",
  "variance",
  "venn diagram",
  "wheel of fortune",
  "with replacement",
  "without replacement",
  "product rule (probability)",
  "associative law",
  "calculator",
  "commutative law",
  "computational method",
  "digital tool",
  "distributive law",
  "divisibility rule",
  "expand bracket",
  "formulary",
  "geometry tool",
  "law of operation",
  "law of radical",
  "order of operation",
  "order of operations",
  "power law",
  "reference point",
  "rule of three",
  "spreadsheet",
  "row",
  "tabular data",
  "series",
  "ability",
  "accuracy",
  "certain",
  "collinearity",
  "completeness",
  "condition",
  "connection",
  "density",
  "dependent",
  "discrete",
  "effect",
  "global",
  "impossible",
  "independent",
  "inversely proportional",
  "local",
  "magnitude relationship",
  "relationship",
  "meaning",
  "oblique",
  "pi",
  "possibility",
  "possible",
  "property",
  "proportional",
  "quantity",
  "relative size",
  "root (graph)",
  "sensible",
  "side",
  "solvable",
  "span",
  "trend",
  "type",
  "various",
  "over 10",
  "topic: number ranges",
  "over 100",
  "over 1000",
  "over 10000",
  "over 100000",
  "over 1000000",
  "over 1000000000",
  "over 1000000000000",
  "over 20",
  "up to 10",
  "up to 100",
  "up to 1000",
  "up to 10000",
  "up to 100000",
  "up to 1000000",
  "up to 1000000000",
  "up to 1000000000000",
  "up to 20",
  "area model",
  "arrow",
  "bar graph",
  "boxplot",
  "diagram",
  "floor plan",
  "frequency table",
  "grid",
  "histogram",
  "map",
  "pie chart",
  "representation",
  "symbol",
  "tally chart",
  "two-way table",
  "word"
] as const
